(* ::Package:: *)

(* ::Input:: *)
(*BeginPackage["Project`"];*)
(**)
(*MyCircularity::usage "circularity[image, method] gives the circularity mesurements of the main shape in the figure 'image' using the method 'method'";*)
(**)
(*(*Begin["Private`"]*)*)
(*MyCircularity[image_, method_, circ_] := *)
(*Module[*)
(*{img = image, algo = method, shape, area, perimeter},*)
(*shape = MorphologicalBinarize[image];*)
(*shape = DeleteSmallComponents[shape];*)
(*area = ComponentMeasurements[shape, "Area"];*)
(*area = area /. Rule -> (#2&);*)
(*area = area[[1]];*)
(*perimeter = ComponentMeasurements[%, "PerimeterLength"];*)
(*perimeter = perimeter/. Rule -> (#2&);*)
(*perimeter = perimeter[[1]];*)
(*(* Plain Circularity *)*)
(*circ = 4*Pi*area/perimeter^2*)
(*]*)
(*(*End[]*)*)
(**)
(**)
(**)
(*MyModule[M_] :=*)
(*Module[{m = M},*)
(*Print["m = ", m];*)
(*Y = m + 1;*)
(*Y*)
(*]*)
(**)
(*EndPackage[]*)
