//
// Generated file, do not edit! Created by opp_msgc 4.5 from LoginMsg.msg.
//

#ifndef _LOGINMSG_M_H_
#define _LOGINMSG_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>LoginMsg.msg</tt> by opp_msgc.
 * <pre>
 * message LoginMsg
 * {
 *     
 * 	int ID;
 * 	
 * 	int x;
 * 	
 * 	int y;
 * }
 * </pre>
 */
class LoginMsg : public ::cMessage
{
  protected:
    int ID_var;
    int x_var;
    int y_var;

  private:
    void copy(const LoginMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LoginMsg&);

  public:
    LoginMsg(const char *name=NULL, int kind=0);
    LoginMsg(const LoginMsg& other);
    virtual ~LoginMsg();
    LoginMsg& operator=(const LoginMsg& other);
    virtual LoginMsg *dup() const {return new LoginMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getID() const;
    virtual void setID(int ID);
    virtual int getX() const;
    virtual void setX(int x);
    virtual int getY() const;
    virtual void setY(int y);
};

inline void doPacking(cCommBuffer *b, LoginMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, LoginMsg& obj) {obj.parsimUnpack(b);}


#endif // _LOGINMSG_M_H_
