//
// Generated file, do not edit! Created by opp_msgc 4.5 from MoveMsg.msg.
//

#ifndef _MOVEMSG_M_H_
#define _MOVEMSG_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>MoveMsg.msg</tt> by opp_msgc.
 * <pre>
 * message MoveMsg
 * {
 *     
 * 	int clientID;
 * 	
 * 	int serverID;
 * 	
 * 	int x;
 * 	int y;
 * 	
 * 	
 * 	int aoi[];    
 * }
 * </pre>
 */
class MoveMsg : public ::cMessage
{
  protected:
    int clientID_var;
    int serverID_var;
    int x_var;
    int y_var;
    int *aoi_var; // array ptr
    unsigned int aoi_arraysize;

  private:
    void copy(const MoveMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MoveMsg&);

  public:
    MoveMsg(const char *name=NULL, int kind=0);
    MoveMsg(const MoveMsg& other);
    virtual ~MoveMsg();
    MoveMsg& operator=(const MoveMsg& other);
    virtual MoveMsg *dup() const {return new MoveMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getClientID() const;
    virtual void setClientID(int clientID);
    virtual int getServerID() const;
    virtual void setServerID(int serverID);
    virtual int getX() const;
    virtual void setX(int x);
    virtual int getY() const;
    virtual void setY(int y);
    virtual void setAoiArraySize(unsigned int size);
    virtual unsigned int getAoiArraySize() const;
    virtual int getAoi(unsigned int k) const;
    virtual void setAoi(unsigned int k, int aoi);
};

inline void doPacking(cCommBuffer *b, MoveMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MoveMsg& obj) {obj.parsimUnpack(b);}


#endif // _MOVEMSG_M_H_
