//
// Generated file, do not edit! Created by opp_msgc 4.5 from UpdateAoIMsg.msg.
//

#ifndef _UPDATEAOIMSG_M_H_
#define _UPDATEAOIMSG_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>UpdateAoIMsg.msg</tt> by opp_msgc.
 * <pre>
 * message UpdateAoIMsg
 * {
 *     
 * 	int clientMoved;
 * 	
 * 	int clientDest;
 * 	
 * 	int serverID;
 * 	
 * 	
 * 	int aoi[];    
 * }
 * </pre>
 */
class UpdateAoIMsg : public ::cMessage
{
  protected:
    int clientMoved_var;
    int clientDest_var;
    int serverID_var;
    int *aoi_var; // array ptr
    unsigned int aoi_arraysize;

  private:
    void copy(const UpdateAoIMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UpdateAoIMsg&);

  public:
    UpdateAoIMsg(const char *name=NULL, int kind=0);
    UpdateAoIMsg(const UpdateAoIMsg& other);
    virtual ~UpdateAoIMsg();
    UpdateAoIMsg& operator=(const UpdateAoIMsg& other);
    virtual UpdateAoIMsg *dup() const {return new UpdateAoIMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getClientMoved() const;
    virtual void setClientMoved(int clientMoved);
    virtual int getClientDest() const;
    virtual void setClientDest(int clientDest);
    virtual int getServerID() const;
    virtual void setServerID(int serverID);
    virtual void setAoiArraySize(unsigned int size);
    virtual unsigned int getAoiArraySize() const;
    virtual int getAoi(unsigned int k) const;
    virtual void setAoi(unsigned int k, int aoi);
};

inline void doPacking(cCommBuffer *b, UpdateAoIMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, UpdateAoIMsg& obj) {obj.parsimUnpack(b);}


#endif // _UPDATEAOIMSG_M_H_
